import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import java.sql.*;
import br.com.projetoapoo.dal.ModuloConexao;
import javax.swing.*;
import java.awt.*;
import java.text.DateFormat;

public class Boundary_ger extends javax.swing.JInternalFrame {

    public Gerente ger;
    public static Control_ger controlGer = new Control_ger();
    public Integer codigo;

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public static Boundary_ger gerGer;

    public Boundary_ger(Integer cod) {
        initComponents();
        conexao = ModuloConexao.conector();
        codigo = cod;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btLimpar = new javax.swing.JButton();
        btAlterar_prod = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        lblGerente = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        ctNome = new javax.swing.JTextField();
        ctCpf = new javax.swing.JTextField();
        lblCpf = new javax.swing.JLabel();
        lblNro = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        ctSenha = new javax.swing.JTextField();
        ctTelefone = new javax.swing.JTextField();
        ctEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Dados de Usuário");
        setPreferredSize(new java.awt.Dimension(898, 609));

        btLimpar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btAlterar_prod.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btAlterar_prod.setText("Atualizar Dados");
        btAlterar_prod.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAlterar_prod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterar_prodActionPerformed(evt);
            }
        });

        btSair.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btSair.setText("Sair");
        btSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        lblGerente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblGerente.setText("Dados de Funcionário");

        lblNome.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNome.setText("*Nome:");

        lblCodigo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCodigo.setText("Código:");

        ctNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctNomeActionPerformed(evt);
            }
        });

        ctCpf.setEditable(false);
        ctCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctCpfActionPerformed(evt);
            }
        });

        lblCpf.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCpf.setText("*CPF:");

        lblNro.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNro.setText("Nº");

        lblSenha.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSenha.setText("*Senha:");

        lblTelefone.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTelefone.setText("Telefone:");

        lblEmail.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblEmail.setText("*E-mail:");

        ctSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctSenhaActionPerformed(evt);
            }
        });

        ctTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctTelefoneActionPerformed(evt);
            }
        });

        ctEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctEmailActionPerformed(evt);
            }
        });

        jLabel1.setText("*Campos Obrigatórios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCodigo)
                            .addComponent(lblSenha)
                            .addComponent(lblEmail)
                            .addComponent(lblNome)
                            .addComponent(lblCpf))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTelefone)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ctCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addComponent(ctEmail)
                    .addComponent(ctNome, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(349, 349, 349)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btLimpar)
                                .addGap(18, 18, 18)
                                .addComponent(btSair))
                            .addComponent(btAlterar_prod, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(ctTelefone)
                    .addComponent(ctSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(149, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblGerente)
                .addGap(349, 349, 349))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblGerente)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(lblNro)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ctCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCpf))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ctNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ctSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSenha))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ctTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefone))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ctEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail))
                .addGap(48, 48, 48)
                .addComponent(btAlterar_prod)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimpar)
                    .addComponent(btSair))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        setBounds(0, 0, 886, 567);
    }// </editor-fold>//GEN-END:initComponents

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btAlterar_prodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterar_prodActionPerformed
        try {
            alterar();
            consultar();
        } catch (NumNegException ex) {
            Logger.getLogger(Boundary_ger.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btAlterar_prodActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void ctNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctNomeActionPerformed

    private void ctCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctCpfActionPerformed

    private void ctSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctSenhaActionPerformed

    private void ctTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctTelefoneActionPerformed

    private void ctEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctEmailActionPerformed

    public void limpar() {
        ctNome.setText("");
        ctCpf.setText("");
        ctSenha.setText("");
        ctTelefone.setText("");
        ctEmail.setText("");
        ctCpf.requestFocus();
    }

    public void sair() {
        int resp = JOptionPane.showConfirmDialog(null, "Deseja sair?", "Saída", JOptionPane.YES_NO_CANCEL_OPTION);
        if (resp == 0) {
            this.dispose();
        }
    }

    public void alterar() throws NumNegException {
        String sql = "update tbgerente set ger_nome = ?, ger_cpf = ?, ger_senha = ?, ger_tel = ?, ger_email = ? where ger_codigo = ?";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, ctNome.getText());
            try {
                if (ctCpf.getText().length() == 11) {
                    pst.setLong(2, Long.parseLong(ctCpf.getText()));
                } else {
                    JOptionPane.showMessageDialog(null, "Digite um CPF válido!", "CPF inválido", 0);
                }
            } catch (NumberFormatException nfe) {
                JOptionPane.showMessageDialog(null, "Digite apenas os números do campo CPF!", "ERRO de CPF", 0);
            }
            if (ctSenha.getText().length() < 15) {
                pst.setString(3, ctSenha.getText());
            } else {
                JOptionPane.showMessageDialog(null, "A senha tem que ter no máximo 15 caracteres!", "Senha grande demais", 0);
            }
            try {
                if (ctTelefone.getText().length() == 11) {
                    pst.setLong(4, Long.parseLong(ctTelefone.getText()));
                } else {
                    JOptionPane.showMessageDialog(null, "Digite apenas os números do Telefone!", "Telefone inválido", 0);

                }
            } catch (NumberFormatException nfe) {
                JOptionPane.showMessageDialog(null, "Digite apenas os números do campo Telefone!", "ERRO em Telefone", 0);
            }
            pst.setString(5, ctEmail.getText());
            pst.setInt(6, codigo);

            if (ctNome.getText().isEmpty() || ctCpf.getText().isEmpty() || ctSenha.getText().isEmpty() || ctEmail.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos obrigatórios!", "Campos Obrigatórios vazios", 0);
            } else {

                int add = pst.executeUpdate();

                if (add > 0) {
                    JOptionPane.showMessageDialog(null, "Dados do Gerente atualizados com sucesso", "Atualização de dados concluida", 1);
                    limpar();
                } else {
                    JOptionPane.showMessageDialog(null, "Dados do Gerente não atualizados", "ERRO de atualização", 0);
                }

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    private void consultar() {

        String sql = "select * from tbgerente where ger_codigo = ?";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setInt(1, codigo);
            rs = pst.executeQuery();
            if (rs.next()) {
                ctNome.setText(rs.getString(2));
                ctCpf.setText(String.valueOf(rs.getLong(3)));
                ctTelefone.setText(String.valueOf(rs.getLong(4)));
                ctSenha.setText(rs.getString(5));
                ctEmail.setText(rs.getString(6));

                JOptionPane.showMessageDialog(null, "Confirme os dados do Gerente", "Confirmacao de Dados", 1);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Integer cod = 0;
                new Boundary_ger(cod).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btAlterar_prod;
    public static javax.swing.JButton btLimpar;
    public static javax.swing.JButton btSair;
    public static javax.swing.JTextField ctCpf;
    public static javax.swing.JTextField ctEmail;
    public static javax.swing.JTextField ctNome;
    public static javax.swing.JTextField ctSenha;
    public static javax.swing.JTextField ctTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGerente;
    private javax.swing.JLabel lblNome;
    public static javax.swing.JLabel lblNro;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTelefone;
    // End of variables declaration//GEN-END:variables

    private void consulta() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
