import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

import java.sql.*;
import br.com.projetoapoo.dal.ModuloConexao_assistente;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author yigor
 */
public class Tela_InicialAss extends javax.swing.JFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    private Integer codigo;
    /**
     * Creates new form Tela_Inicial
     */
    public Tela_InicialAss(Integer cod) {
        initComponents();
        conexao = ModuloConexao_assistente.conector();
        codigo = cod;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        desktop = new javax.swing.JDesktopPane();
        lblUsuario = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MnConta = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        MnRel_Prod = new javax.swing.JMenuItem();
        MnRel__Estoq = new javax.swing.JMenuItem();
        MnRel_Gerentes = new javax.swing.JMenuItem();
        MnOpcoes = new javax.swing.JMenu();
        MnSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gerência de uma Loja de Hardware");
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("LCDMono2", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setText("LOJA DE HARDWARE");

        desktop.setPreferredSize(new java.awt.Dimension(898, 609));

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 609, Short.MAX_VALUE)
        );

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsuario.setText("Gerente");

        lblData.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblData.setText("Data");

        jMenu1.setText("Minha Conta");

        MnConta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_DOWN_MASK));
        MnConta.setText("Acessar");
        MnConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnContaActionPerformed(evt);
            }
        });
        jMenu1.add(MnConta);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Consultas");

        MnRel_Prod.setText("Relatórios de Produtos");
        MnRel_Prod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnRel_ProdActionPerformed(evt);
            }
        });
        jMenu3.add(MnRel_Prod);

        MnRel__Estoq.setText("Relatórios de Estoque");
        MnRel__Estoq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnRel__EstoqActionPerformed(evt);
            }
        });
        jMenu3.add(MnRel__Estoq);

        MnRel_Gerentes.setText("Relatórios de Gerentes");
        MnRel_Gerentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnRel_GerentesActionPerformed(evt);
            }
        });
        jMenu3.add(MnRel_Gerentes);

        jMenuBar1.add(jMenu3);

        MnOpcoes.setText("Opções");
        MnOpcoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnOpcoesActionPerformed(evt);
            }
        });

        MnSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        MnSair.setText("Sair");
        MnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnSairActionPerformed(evt);
            }
        });
        MnOpcoes.add(MnSair);

        jMenuBar1.add(MnOpcoes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 354, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsuario, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblData, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(81, 81, 81))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(lblData))
                    .addComponent(lblUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(926, 709));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnSairActionPerformed
        // exibe uma caixa de diálogo
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?", "Atenção", JOptionPane.YES_NO_OPTION);
        if(sair == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_MnSairActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // as linhas abaixo substituem a label lblData pela data atual do sistema ao iniciar o form
        Date data = new Date();
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.SHORT);
        lblData.setText(formatador.format(data));
    }//GEN-LAST:event_formWindowActivated

    private void MnOpcoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnOpcoesActionPerformed
        
    }//GEN-LAST:event_MnOpcoesActionPerformed

    private void MnRel_ProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnRel_ProdActionPerformed
        Relatoro_Prod rel = new Relatoro_Prod();
        rel.setVisible(true);
        desktop.add(rel);
        desktop.moveToFront(rel);
    }//GEN-LAST:event_MnRel_ProdActionPerformed

    private void MnRel_GerentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnRel_GerentesActionPerformed
        Relatorio_Ger rel = new Relatorio_Ger();
        rel.setVisible(true);
        desktop.add(rel);
        desktop.moveToFront(rel);
    }//GEN-LAST:event_MnRel_GerentesActionPerformed

    private void MnContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnContaActionPerformed
        Boundary_ass ass = new Boundary_ass(codigo);
        ass.setVisible(true);
        ass.lblNro.setText(String.valueOf(codigo));
        String sql = "select * from tbassistente where ass_codigo = ?";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setInt(1, codigo);
            rs = pst.executeQuery();
                if (rs.next()) {
                    ass.ctNome.setText(rs.getString(2));
                    ass.ctCpf.setText(String.valueOf(rs.getLong(3)));
                    ass.ctTelefone.setText(String.valueOf(rs.getLong(4)));
                    ass.ctSenha.setText(rs.getString(5));
                    ass.ctEmail.setText(rs.getString(6));
                    desktop.add(ass);
                    desktop.moveToFront(ass);
                }
        } catch (SQLException ex) {
            Logger.getLogger(Tela_InicialAss.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MnContaActionPerformed

    private void MnRel__EstoqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnRel__EstoqActionPerformed
        Relatorio_Estoq rel = new Relatorio_Estoq();
        rel.setVisible(true);
        desktop.add(rel);
        desktop.moveToFront(rel);
    }//GEN-LAST:event_MnRel__EstoqActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_InicialGer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_InicialGer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_InicialGer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_InicialGer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                int cod = 0;
                new Tela_InicialAss(cod).setVisible(true);
                View_Inicial view = new View_Inicial();
                view.setVisible(true);
                desktop.add(view);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MnConta;
    private javax.swing.JMenu MnOpcoes;
    private javax.swing.JMenuItem MnRel_Gerentes;
    private javax.swing.JMenuItem MnRel_Prod;
    private javax.swing.JMenuItem MnRel__Estoq;
    private javax.swing.JMenuItem MnSair;
    public static javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblData;
    public static javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables

}
