import java.sql.*;
import br.com.projetoapoo.dal.ModuloConexao;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author yigor
 */
public class View_Inicial extends javax.swing.JInternalFrame {

    /**
     * Creates new form View_Inicial
     */
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public static View_Inicial view;
    
    public void ShowTable() {
        String sql = "select prod_codigo, prod_nome, prod_descricao, prod_marca, prod_modelo, prod_preco, prod_categoria from tbproduto";
        try {
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            DefaultTableModel model = (DefaultTableModel) TabProd.getModel();
            model.setRowCount(0);

            String codigo, nome, descricao, marca, modelo, preco, categoria;
            while (rs.next()) {
                codigo = rs.getString(1);
                nome = rs.getString(2);
                descricao = rs.getString(3);
                marca = rs.getString(4);
                modelo = rs.getString(5);
                preco = rs.getString(6);
                categoria = rs.getString(7);
                String[] row = {codigo, nome, descricao, marca, modelo, preco, categoria};
                model.addRow(row);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public View_Inicial() {
        initComponents();
        conexao = ModuloConexao.conector();
        ShowTable();
    }
    
    private void pesquisar_produto(){
        String sql = "select prod_codigo, prod_nome, prod_descricao, prod_marca, prod_modelo, prod_preco, prod_categoria from tbproduto where prod_nome like ?";
        try {
            pst = conexao.prepareStatement(sql);
            //passando o conteúdo da caixa de pesquisa para o ?
            //atenção ao % - continuação da String sql
            pst.setString(1, ctPesquisa.getText() + "%");
            rs = pst.executeQuery();
            //a linha abaixo usa a biblioteca rs2xml.jar para preencher a tabela
            TabProd.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public static View_Inicial getView_Inicial() {
        if (view == null) {
            view = new View_Inicial();
        }
        return view;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        ctPesquisa = new javax.swing.JTextField();
        lblSearch = new javax.swing.JLabel();
        ScrollProd = new javax.swing.JScrollPane();
        TabProd = new javax.swing.JTable();
        pnlMenu = new javax.swing.JPanel();
        pnlCateg = new javax.swing.JPanel();
        lblCateg = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstMenu = new javax.swing.JList<>();
        btnAll = new javax.swing.JButton();

        setIconifiable(true);
        setMaximizable(true);

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(0, 102, 0));

        ctPesquisa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ctPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ctPesquisaKeyReleased(evt);
            }
        });

        lblSearch.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\icones\\search.png"));
        lblSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSearchMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(ctPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSearch)
                    .addComponent(ctPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        ScrollProd.setBackground(new java.awt.Color(204, 204, 204));

        TabProd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TabProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Produto", "Descrição", "Marca", "Modelo", "Preço", "Categoria"
            }
        )
        {
            public boolean isCellEditable(int row, int column){
                return false;
            }
        }
    );
    ScrollProd.setViewportView(TabProd);

    pnlMenu.setBackground(new java.awt.Color(0, 0, 0));

    pnlCateg.setBackground(new java.awt.Color(0, 0, 0));
    pnlCateg.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            pnlCategMouseClicked(evt);
        }
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            pnlCategMouseEntered(evt);
        }
        public void mouseExited(java.awt.event.MouseEvent evt) {
            pnlCategMouseExited(evt);
        }
    });

    lblCateg.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    lblCateg.setForeground(new java.awt.Color(255, 255, 255));
    lblCateg.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\icones\\menu.png"));
    lblCateg.setText("Categoria");

    lstMenu.setBackground(new java.awt.Color(0, 0, 0));
    lstMenu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    lstMenu.setForeground(new java.awt.Color(255, 255, 255));
    lstMenu.setModel(new javax.swing.AbstractListModel<String>() {
        String[] strings = { "HD", "SSD", "Memória RAM", "Memória Corsair", "Memória Adata", "Fonte", "Processador", "Placa mãe", "Periféricos", "Monitores" };
        public int getSize() { return strings.length; }
        public String getElementAt(int i) { return strings[i]; }
    });
    lstMenu.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
        public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
            lstMenuValueChanged(evt);
        }
    });
    jScrollPane3.setViewportView(lstMenu);

    javax.swing.GroupLayout pnlCategLayout = new javax.swing.GroupLayout(pnlCateg);
    pnlCateg.setLayout(pnlCategLayout);
    pnlCategLayout.setHorizontalGroup(
        pnlCategLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pnlCategLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(pnlCategLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlCategLayout.createSequentialGroup()
                    .addComponent(lblCateg)
                    .addGap(0, 0, Short.MAX_VALUE))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
            .addContainerGap())
    );
    pnlCategLayout.setVerticalGroup(
        pnlCategLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pnlCategLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(lblCateg)
            .addGap(18, 18, 18)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
    pnlMenu.setLayout(pnlMenuLayout);
    pnlMenuLayout.setHorizontalGroup(
        pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(pnlCateg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    pnlMenuLayout.setVerticalGroup(
        pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pnlMenuLayout.createSequentialGroup()
            .addComponent(pnlCateg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
    );

    btnAll.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    btnAll.setText("Consultar todos os Produtos");
    btnAll.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            btnAllMouseClicked(evt);
        }
    });

    jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jDesktopPane1.setLayer(ScrollProd, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jDesktopPane1.setLayer(pnlMenu, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jDesktopPane1.setLayer(btnAll, javax.swing.JLayeredPane.DEFAULT_LAYER);

    javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
    jDesktopPane1.setLayout(jDesktopPane1Layout);
    jDesktopPane1Layout.setHorizontalGroup(
        jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jDesktopPane1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(btnAll)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(ScrollProd, javax.swing.GroupLayout.PREFERRED_SIZE, 834, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(22, Short.MAX_VALUE))
    );
    jDesktopPane1Layout.setVerticalGroup(
        jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jDesktopPane1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 46, Short.MAX_VALUE))
            .addGap(18, 18, 18)
            .addComponent(btnAll)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
            .addComponent(ScrollProd, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(16, 16, 16))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jDesktopPane1)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jDesktopPane1)
    );

    setBounds(0, 0, 874, 566);
    }// </editor-fold>//GEN-END:initComponents

    private void pnlCategMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCategMouseClicked
        if(pnlMenu.getHeight() == 60){
            pnlMenu.setSize(170, 380);
        }else{
            pnlMenu.setSize(170, 60);
        }
        //System.out.println(pnlMenu.getHeight());
    }//GEN-LAST:event_pnlCategMouseClicked

    private void pnlCategMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCategMouseEntered

    }//GEN-LAST:event_pnlCategMouseEntered

    private void pnlCategMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCategMouseExited

    }//GEN-LAST:event_pnlCategMouseExited

    private void lstMenuValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstMenuValueChanged
        
        String sql = "select prod_codigo, prod_nome, prod_descricao, prod_marca, prod_modelo, prod_preco, prod_categoria from tbproduto where prod_categoria = ?";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, lstMenu.getSelectedValue());
            rs = pst.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            DefaultTableModel model = (DefaultTableModel) TabProd.getModel();
            model.setRowCount(0);

            String codigo, nome, descricao, marca, modelo, preco, categoria;
            while (rs.next()) {
                codigo = rs.getString(1);
                nome = rs.getString(2);
                descricao = rs.getString(3);
                marca = rs.getString(4);
                modelo = rs.getString(5);
                preco = rs.getString(6);
                categoria = rs.getString(7);
                String[] row = {codigo, nome, descricao, marca, modelo, preco, categoria};
                model.addRow(row);
                pnlMenu.setSize(170, 60);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_lstMenuValueChanged

    private void lblSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSearchMouseClicked
        ShowTable();
    }//GEN-LAST:event_lblSearchMouseClicked

    private void btnAllMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAllMouseClicked
        ShowTable();
    }//GEN-LAST:event_btnAllMouseClicked

    private void ctPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ctPesquisaKeyReleased
        // o evento abaixo é do tipo "enquanto for digitando"
        //chamar o método pesquisar produtos
        pesquisar_produto();
    }//GEN-LAST:event_ctPesquisaKeyReleased

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_Inicial().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollProd;
    private javax.swing.JTable TabProd;
    private javax.swing.JButton btnAll;
    private javax.swing.JTextField ctPesquisa;
    public static javax.swing.JDesktopPane jDesktopPane1;
    public static javax.swing.JPanel jPanel1;
    public static javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JLabel lblCateg;
    public static javax.swing.JLabel lblSearch;
    public static javax.swing.JList<String> lstMenu;
    public static javax.swing.JPanel pnlCateg;
    public static javax.swing.JPanel pnlMenu;
    // End of variables declaration//GEN-END:variables
}
